### ISSUE TITLE
Dependency conflict on requirements.txt

### ISSUE THREAD

**Issue by A-atmos** [ossf/omega-triage-portal#35]
`requests==2.28.1` depends on `charset-normalizer < 3` and `>=2` but `charset-normalizer` is explicitly set to v`3.1.0` which causes conflict on dependency.
Remedy: Upgrade `requests` to `2.28.2`.
![image](https://user-images.githubusercontent.com/68424695/231524739-074a3644-949d-4415-a786-9a9ab6675e7c.png)

**Comment by ropwareJB** [comment]
Thanks for raising this @A-atmos, main branch has been updated.

**Comment by Cyber-JiuJiteria** [comment]
Dependabot updates have been merged and dependency conflicts patched in latest PR. closing issue. please let me know if issue reoccurs
