### ISSUE TITLE
File.py git conflict in file

### ISSUE THREAD

**Issue by ropwareJB** [ossf/omega-triage-portal#38]
https://github.com/ossf/omega-triage-portal/blob/main/src/triage/models/file.py (main as of 2023-04-13, [b8c7222](https://github.com/ossf/omega-triage-portal/commit/b8c722287adaa746e2be41e7ddd980d35bc3a435)) has a git merge conflict in-file.

```
<<<<<<< HEAD:src/triage/models/File.py
from __future__ import annotations

import hashlib
=======
>>>>>>> main:src/triage/models/file.py
import base64
import hashlib
import logging
```

**Comment by Cyber-JiuJiteria** [comment]
Hey @ropwareJB I patched this in the [azure_docker_workflow](https://github.com/ossf/omega-triage-portal/tree/azure_docker_workflow) branch. Thank you for submitting it. I will send out a pull request, once Azure is troubleshooted and triage portal is live.
